local M = {}

M.kind_icons = {
  Module = ' ',
  Namespace = ' ',
  Package = ' ',
  Class = ' ',
  Method = ' ',
  Property = ' ',
  Field = ' ',
  Constructor = ' ',
  Enum = ' ',
  Interface = ' ',
  Function = ' ',
  Variable = ' ',
  Constant = ' ',
  String = ' ',
  Number = ' ',
  Boolean = ' ',
  Array = ' ',
  Object = ' ',
  Key = ' ',
  Null = ' ',
  EnumMember = ' ',
  Struct = ' ',
  Event = ' ',
  Operator = ' ',
  TypeParameter = ' ',
  Text = ' ',
  Unit = ' ',
  Value = ' ',
  Keyword = ' ',
  Color = ' ',
  Reference = ' ',
  Snippet = ' ',
  File = ' ',
  Folder = ' ',
}

return M
